# Generated by Django 5.1.6 on 2025-02-27 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_discount_tax_item_currency_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='stripe_payment_intent',
        ),
    ]
